### ISSUE TITLE
Add NA catch for detect cores

### ISSUE THREAD

**Issue by skgrange** [skgrange/rmweather#1]
An example of the error: 
```
Error in if (x < 16) { : missing value where TRUE/FALSE needed
> parallel::detectCores()
[1] NA
```

I have not seen this, but it has been reported to me and can easily handled.

**Comment by jachymcz** [comment]
This seems like a great and useful package, but it looks like it requires some deprecated code:

Warning message:
`data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
