### ISSUE TITLE
Error message regarding ranger when using the normalise code

### ISSUE THREAD

**Issue by Medgar21** [skgrange/rmweather#4]
Hi there,

Apologies if this is a stupid question.

I am attempting to normalise a data set including hourly o3 values and relevant meteorological variables in 2016.
When using the following code:

normalised_o3_bl_2016 <- rmw_do_all(
  df = o3_bl_2016_prepared,
  variables = c(
     "air_temp", "dew", "atm_pressure", "wd", "ws", "date_unix", "day_julian", "weekday", "hour"
  ),
  n_trees = 300,
  n_samples = 300
)

I get this error message:
Error in ranger::ranger(value ~ ., data = df, write.forest = TRUE, importance = "permutation",  : 
  Error: Unsupported type of dependent variable.

All my variables are numerical and when rerunning the code with some variables removed, in an attempt to locate the variable causing the issue, it results in the same error message. 
My csv file is of the same layout as the example data file.

Thanks for any help you can provide.

**Comment by skgrange** [comment]
Hello. An interesting issue you have there. Almost certainly this is a data-type issue. Could you please provide the results of `str(o3_bl_2016_prepared)`? Another thing to check is if your data frame/tibble contains `NULL`s. This may give issues for the logic in ranger.

**Comment by Medgar21** [comment]
Thank you for your response. 

It turns out it was a simple mistake in excel where the values with greater decimal places had been rounded on appearance but not input.

Thank you for your help!

**Comment by skgrange** [comment]
Good to hear. Enjoy!
